/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/AEBDoorDrawing.glb 
*/

import React, { useMemo } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/assets/AEBDoorDrawing.glb");

  // Define a palette of colors to cycle through
  const colors = [
    "#e63946", // Red
    "#f1faee", // White/Ice
    "#a8dadc", // Light Blue
    "#457b9d", // Blue
    "#1d3557", // Dark Blue
    "#2a9d8f", // Teal
    "#e9c46a", // Yellow
    "#f4a261", // Orange
    "#e76f51", // Burnt Orange
    "#606c38", // Olive
    "#283618", // Dark Green
  ];

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Obj212.geometry}
        material-color={colors[0 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj229.geometry}
        material-color={colors[1 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj241.geometry}
        material-color={colors[2 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj213.geometry}
        material-color={colors[3 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj195.geometry}
        material-color={colors[4 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj148.geometry}
        material-color={colors[5 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj240.geometry}
        material-color={colors[6 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj242.geometry}
        material-color={colors[7 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj243.geometry}
        material-color={colors[8 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj173.geometry}
        material-color={colors[9 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj196.geometry}
        material-color={colors[10 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj2121.geometry}
        material-color={colors[11 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj198.geometry}
        material-color={colors[12 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj209.geometry}
        material-color={colors[13 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj214.geometry}
        material-color={colors[14 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj1481.geometry}
        material-color={colors[15 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj1951.geometry}
        material-color={colors[16 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj225.geometry}
        material-color={colors[17 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj226.geometry}
        material-color={colors[18 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj210.geometry}
        material-color={colors[19 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj1731.geometry}
        material-color={colors[20 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj1961.geometry}
        material-color={colors[21 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj2251.geometry}
        material-color={colors[22 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj2261.geometry}
        material-color={colors[23 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj2131.geometry}
        material-color={colors[24 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj2091.geometry}
        material-color={colors[25 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj227.geometry}
        material-color={colors[26 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj266.geometry}
        material-color={colors[27 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj267.geometry}
        material-color={colors[28 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj644.geometry}
        material-color={colors[29 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj2101.geometry}
        material-color={colors[30 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj2271.geometry}
        material-color={colors[31 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj254.geometry}
        material-color={colors[32 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj265.geometry}
        material-color={colors[33 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj228.geometry}
        material-color={colors[34 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj2291.geometry}
        material-color={colors[35 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj2411.geometry}
        material-color={colors[36 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj610.geometry}
        material-color={colors[37 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj609.geometry}
        material-color={colors[38 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj465.geometry}
        material-color={colors[39 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj466.geometry}
        material-color={colors[40 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj6101.geometry}
        material-color={colors[41 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj6091.geometry}
        material-color={colors[42 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj2431.geometry}
        material-color={colors[43 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj723.geometry}
        material-color={colors[44 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj678.geometry}
        material-color={colors[45 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj6441.geometry}
        material-color={colors[46 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj574.geometry}
        material-color={colors[47 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj572.geometry}
        material-color={colors[48 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj556.geometry}
        material-color={colors[49 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj570.geometry}
        material-color={colors[50 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj500.geometry}
        material-color={colors[51 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj707.geometry}
        material-color={colors[52 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj708.geometry}
        material-color={colors[53 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj575.geometry}
        material-color={colors[54 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj573.geometry}
        material-color={colors[55 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj571.geometry}
        material-color={colors[56 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj569.geometry}
        material-color={colors[57 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj4651.geometry}
        material-color={colors[58 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj4661.geometry}
        material-color={colors[59 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj738.geometry}
        material-color={colors[60 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj7071.geometry}
        material-color={colors[61 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj7081.geometry}
        material-color={colors[62 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj7231.geometry}
        material-color={colors[63 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj5561.geometry}
        material-color={colors[64 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj5701.geometry}
        material-color={colors[65 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj5721.geometry}
        material-color={colors[66 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj5741.geometry}
        material-color={colors[67 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj5001.geometry}
        material-color={colors[68 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj5691.geometry}
        material-color={colors[69 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj5711.geometry}
        material-color={colors[70 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj5731.geometry}
        material-color={colors[71 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj5751.geometry}
        material-color={colors[72 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj7381.geometry}
        material-color={colors[73 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj649.geometry}
        material-color={colors[74 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj6781.geometry}
        material-color={colors[75 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj683.geometry}
        material-color={colors[76 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj514.geometry}
        material-color={colors[77 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj515.geometry}
        material-color={colors[78 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj516.geometry}
        material-color={colors[79 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj517.geometry}
        material-color={colors[80 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj518.geometry}
        material-color={colors[81 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj510.geometry}
        material-color={colors[82 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj511.geometry}
        material-color={colors[83 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj509.geometry}
        material-color={colors[84 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj505.geometry}
        material-color={colors[85 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj508.geometry}
        material-color={colors[86 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj506.geometry}
        material-color={colors[87 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj507.geometry}
        material-color={colors[88 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj512.geometry}
        material-color={colors[89 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj513.geometry}
        material-color={colors[90 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj6491.geometry}
        material-color={colors[91 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj6831.geometry}
        material-color={colors[92 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj5171.geometry}
        material-color={colors[93 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj5181.geometry}
        material-color={colors[94 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj5111.geometry}
        material-color={colors[95 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj5121.geometry}
        material-color={colors[96 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj5161.geometry}
        material-color={colors[97 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj5151.geometry}
        material-color={colors[98 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj5061.geometry}
        material-color={colors[99 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj5141.geometry}
        material-color={colors[100 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj5131.geometry}
        material-color={colors[101 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj5081.geometry}
        material-color={colors[102 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj5071.geometry}
        material-color={colors[103 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj5091.geometry}
        material-color={colors[104 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj5051.geometry}
        material-color={colors[105 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj5101.geometry}
        material-color={colors[106 % colors.length]}
      />
    </group>
  );
}

useGLTF.preload("/assets/AEBDoorDrawing.glb");
