/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/AEBT1003DModel.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/assets/AEBT1003DModel.glb");

  // Define a palette of colors to cycle through
  const colors = [
    "#e63946", // Red
    "#f1faee", // White/Ice
    "#a8dadc", // Light Blue
    "#457b9d", // Blue
    "#1d3557", // Dark Blue
    "#2a9d8f", // Teal
    "#e9c46a", // Yellow
    "#f4a261", // Orange
    "#e76f51", // Burnt Orange
    "#606c38", // Olive
    "#283618", // Dark Green
  ];

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Obj173.geometry}
        material-color={colors[0 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj184.geometry}
        material-color={colors[1 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj185.geometry}
        material-color={colors[2 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj186.geometry}
        material-color={colors[3 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj187.geometry}
        material-color={colors[4 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj188.geometry}
        material-color={colors[5 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj190.geometry}
        material-color={colors[6 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj225.geometry}
        material-color={colors[7 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj189.geometry}
        material-color={colors[8 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj161.geometry}
        material-color={colors[9 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj226.geometry}
        material-color={colors[10 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj227.geometry}
        material-color={colors[11 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj232.geometry}
        material-color={colors[12 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj213.geometry}
        material-color={colors[13 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj224.geometry}
        material-color={colors[14 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj201.geometry}
        material-color={colors[15 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj212.geometry}
        material-color={colors[16 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj230.geometry}
        material-color={colors[17 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj231.geometry}
        material-color={colors[18 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj235.geometry}
        material-color={colors[19 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj236.geometry}
        material-color={colors[20 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj1901.geometry}
        material-color={colors[21 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj228.geometry}
        material-color={colors[22 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj229.geometry}
        material-color={colors[23 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj233.geometry}
        material-color={colors[24 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj234.geometry}
        material-color={colors[25 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj2251.geometry}
        material-color={colors[26 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj436.geometry}
        material-color={colors[27 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj2271.geometry}
        material-color={colors[28 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj2321.geometry}
        material-color={colors[29 % colors.length]}
      />
      <mesh
        geometry={nodes.Obj4361.geometry}
        material-color={colors[30 % colors.length]}
      />
    </group>
  );
}

useGLTF.preload("/assets/AEBT1003DModel.glb");
