/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/model.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function GeneratedModel(props) {
  const { nodes, materials } = useGLTF("/assets/model.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Obj422.geometry} material={materials["Obj.422"]} />
    </group>
  );
}

useGLTF.preload("/assets/model.glb");
